#!/bin/bash
red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)
echo "Enter a string"
read string
length=$(echo "$string" | grep -o '[^ ,]'  | wc -l)
if [ "$length" -gt 500 ]
then
echo "${red}${length}${reset}" 
else
echo "${green}${length}${reset}"
fi
